### ISSUE TITLE
Problem with loading files from `graphGallery`

### ISSUE THREAD

**Issue by wchodor** [pbiecek/archivist#138] opened 2015-11-26 19:50 UTC
It is not the first time when I get this kind of message while loading files from `graphGallery`.  @MarcinKosinski received the same mistake and the only solution to this is to reinstall archivist package.@pbiecek Is it possible to create once again this repository. I suppose that there is something wrong with it. Here is the code and error message I get:
```
> library(archivist)
> library(archivist)
> setLocalRepo(system.file("graphGallery", package = "archivist"))
> pl <- aread("2166dfbd3a7a68a91a2f8e6df1a44111")
 Show Traceback
 
 Rerun with Debug
 Error in load(file = file.path(repoDir, "gallery", paste0(md5hash[i],  : 
  input has been corrupted, with LF replaced by CR 
```

**Comment by pbiecek** [comment] 2015-11-26 22:55
Strange, it is working for me (version 1.8.2)
so what is the problem, is it like there is no
2166dfbd3a7a68a91a2f8e6df1a44111.rda file in your repository?
P

2015-11-26 20:50 GMT+01:00 Witold Chodor <notifications@github.com>:

> It is not the first time when I get this kind of message while loading
> files from graphGallery. @MarcinKosinski
> <https://github.com/MarcinKosinski> received the same mistake and the
> only solution to this is to reinstall archivist package.@pbiecek
> <https://github.com/pbiecek> Is it possible to create once again this
> repository. I suppose that there is something wrong with it. Here is the
> code and error message I get:
>
> > library(archivist)
> > library(archivist)
> > setLocalRepo(system.file("graphGallery", package = "archivist"))
> > pl <- aread("2166dfbd3a7a68a91a2f8e6df1a44111")
>  Show Traceback
>
>  Rerun with Debug
>  Error in load(file = file.path(repoDir, "gallery", paste0(md5hash[i],  :
>   input has been corrupted, with LF replaced by CR
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/138>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment] 2015-11-26 22:57
The problems sometimes resolves when you reinstall archivist from github and then you restart and terminate RStudio :)

**Comment by pbiecek** [comment] 2015-11-26 22:59
So maybe it's because you try to write to this repository?
R libraries may be read only and this repository is in the R library tree.
P

2015-11-26 23:57 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> The problems sometimes resolves when you reinstall archivist from github
> and then you restart and terminate RStudio :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/138#issuecomment-160002056>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment] 2015-11-26 23:16
If you check the description of the `aread`:

aread reads an artifact from a Github Repository. It's a wrapper around
loadFromGithubRepo.


So this won't work for local repository :) this is only github-version
functionality.

> This isn't a bug, it's a feature.

2015-11-26 23:59 GMT+01:00 Przemysław Biecek <notifications@github.com>:

**Comment by wchodor** [comment] 2015-11-26 23:23
@MarcinKosinski  This is not TRUE. I have updated this info in this commit: https://github.com/wchodor/archivist/commit/977dbde492c9e7045abb768eebcbf40de33a6252 
`aread` enables a user to read artifact from local and github repo (see the code of this function).

**Comment by MarcinKosinski** [comment] 2015-11-26 23:23
This example dos not work, becuase there isn't such an artifact in the archivist repository. For every other `md5hash` that exist in the archivist repository this works.

This `2166dfbd3a7a68a91a2f8e6df1a44111` md5hash is a hash of the object that is stored on the github repository `pbiecek/graphGallery` and not on the `pbiecek/archivist` with the subdirectory `graphGallery` that is being stored localy.

There was a mistaken md5hash in the example + I think the documentation should be extended as the code looks like to work for local functions :)




````{R}
> library(archivist)
Welcome to archivist (version: 1.8.12.0).
> # read the object from local directory
> setLocalRepo(system.file("graphGallery", package = "archivist"))
> pl <- aread("2166dfbd3a7a68a91a2f8e6df1a44111")
 Show Traceback
 
 Rerun with Debug
 Error in load(file = file.path(repoDir, "gallery", paste0(md5hash[i],  : 
  input has been corrupted, with LF replaced by CR > # plot it
> pl

Call:
lm(formula = Petal.Length ~ Species, data = iris)

Coefficients:
      (Intercept)  Speciesversicolor   Speciesvirginica  
            1.462              2.798              4.090  

> unique(showLocalRepo()[,2])
 [1] "hourly_delay"                                                                                                                             
 [2] "flights %>% group_by(carrier, flight, dest) %>% filter(n() ==     365)"                                                                   
 [3] "flights %>% group_by(dest) %>% summarise(arr_delay = mean(arr_delay,     na.rm = TRUE), n = n()) %>% arrange(desc(arr_delay))"            
 [4] "flights %>% group_by(carrier, flight, dest) %>% tally(sort = TRUE) %>%     filter(n == 365)"                                              
 [5] "per_hour"                                                                                                                                 
 [6] "qplot(time, arr_delay, data = per_hour)"                                                                                                  
 [7] "7c2aa04c304c0e7995ad22df07a25354"                                                                                                         
 [8] "scale_size_area()"                                                                                                                        
 [9] "geom_point()"                                                                                                                             
[10] "(ggplot(filter(per_hour, n > 30), aes(time, arr_delay)) + geom_vline(xintercept = 5:24,     colour = \"white\", size = 2) + geom_point())"
[11] "c112c80ae9039b658149e1d66e7507e9"                                                                                                         
[12] "pl"                                                                                                                                       
[13] "model"                                                                                                                                    
[14] "lhs_val"                                                                                                                                  
[15] "res_val"                                                                                                                                  
[16] "7f11e03539d48d35f7e7fe7780527ba7"                                                                                                         
[17] "0a82efeb8250a47718cea9d7f64e5ae7"                                                                                                         
[18] "d3696e13d15223c7d0bbccb33cc20a11"                                                                                                         
[19] "990861c7c27812ee959f10e5f76fe2c3"                                                                                                         
[20] "050e41ec3bc40b3004bc6bdd356acae7"                                                                                                         
[21] "ff575c261c949d073b2895b05d1097c3"                                                                                                         
[22] "pl2"                                                                                                                                      
[23] "model2"                                                                                                                                   
> smth <- aread('ff575c261c949d073b2895b05d1097c3')
> head(smth)
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa
````

**Comment by pbiecek** [comment] 2015-11-26 23:30
Ok, so the problem is that doc is not updated.
In the first version it was only for github, but now it is working for
local repo as well

P

2015-11-27 0:16 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> If you check the description of the `aread`:
>
> aread reads an artifact from a Github Repository. It's a wrapper around
> loadFromGithubRepo.
>
>
> So this won't work for local repository :) this is only github-version
> functionality.
>
> > This isn't a bug, it's a feature.
>
> 2015-11-26 23:59 GMT+01:00 Przemysław Biecek <notifications@github.com>:
>
> > So maybe it's because you try to write to this repository?
> > R libraries may be read only and this repository is in the R library
> tree.
> > P
> >
> > 2015-11-26 23:57 GMT+01:00 Marcin Kosiński <notifications@github.com>:
> >
> > > The problems sometimes resolves when you reinstall archivist from
> github
> > > and then you restart and terminate RStudio :)
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/pbiecek/archivist/issues/138#issuecomment-160002056
> > >.
> > >
> >
> >
> >
> > --
> > pozdrawiam serdecznie,
> > Przemysław Biecek
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pbiecek/archivist/issues/138#issuecomment-160002192
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/138#issuecomment-160003610>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment] 2015-11-26 23:32
It is interesting because I managed to load this artifact :). It is in graphGallery.
```
> setLocalRepo(system.file("graphGallery", package = "archivist"))
> getTagsLocal("2166dfbd3a7a68a91a2f8e6df1a44111")
[1] "name:pl"
> searchInLocalRepo(pattern = "name:pl")
[1] "2166dfbd3a7a68a91a2f8e6df1a44111" "d74472d5b4eee352ba17c5a6f2472c07"
[3] "92ada1e052d4d963e5787bfc9c4b506c" "25fbc8bc66bbf02fe66b7715ff53b083"
[5] "74f24b7c337263b76753e93cad964480"
> 
```

**Comment by pbiecek** [comment] 2015-11-26 23:33
Same for me,
I have this artifact
it's in the database
sort(unique(showLocalRepo()[,1]))

and in the repo

2015-11-27 0:32 GMT+01:00 Witold Chodor <notifications@github.com>:

> It is interesting because I managed to load this artifact :). It is in
> graphGallery.
>
> > setLocalRepo(system.file("graphGallery", package = "archivist"))
> > getTagsLocal("2166dfbd3a7a68a91a2f8e6df1a44111")
> [1] "name:pl"
> > searchInLocalRepo(pattern = "name:pl")
> [1] "2166dfbd3a7a68a91a2f8e6df1a44111" "d74472d5b4eee352ba17c5a6f2472c07"
> [3] "92ada1e052d4d963e5787bfc9c4b506c" "25fbc8bc66bbf02fe66b7715ff53b083"
> [5] "74f24b7c337263b76753e93cad964480"
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/138#issuecomment-160004594>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by wchodor** [comment] 2015-11-26 23:38
When it comes to doc. I made a request today about it. But nobody merged it.

**Comment by MarcinKosinski** [comment] 2015-11-26 23:41
After reinstall it worked...
Which request you ment?

2015-11-27 0:39 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment] 2015-11-26 23:42
https://github.com/wchodor/archivist/commit/977dbde492c9e7045abb768eebcbf40de33a6252

**Comment by MarcinKosinski** [comment] 2015-11-26 23:44
It has conflicts (I am trying to solve this). And it was open 2 hours ago :)

2015-11-27 0:42 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment] 2015-11-26 23:44
I send you a mail :)

**Comment by MarcinKosinski** [comment] 2015-11-27 00:20
I don't see such an e-mail. 
What's the point of complaining about not merged PR after 2h when it was submitted almost at midnight?

**Comment by pbiecek** [comment] 2015-11-27 06:56
I missed this merge as well,
but it is great that Witek updates the docs.
I can merge it around 10am

2015-11-27 1:20 GMT+01:00 Marcin Kosiński <notifications@github.com>:

> I don't see such an e-mail.
> What's the point of complaining about not merged PR after 2h when it was
> submitted almost at midnight?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/138#issuecomment-160010722>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by MarcinKosinski** [comment] 2015-11-29 16:16
Ok, so what's the recipe for this situation?

**Closed** 2015-12-28 22:28 UTC
