### ISSUE TITLE
Extend tags in `extractTags`

### ISSUE THREAD

**Issue by wchodor** [pbiecek/archivist#154] opened 2015-12-01 20:24 UTC

**Comment by wchodor** [comment] 2015-12-04 17:01
@pbiecek @MarcinKosinski 
I was trying to extend tags in `htest` object and I received the following error:
```
> library(archivist)
Welcome to archivist (version: 1.9.1.1).
> library(gamair)
> data(wine)
> htestcor <- cor.test(wine$year, wine$s.temp, method = "pearson")
> exampleRepoDir <- tempfile()
> createEmptyRepo( repoDir = exampleRepoDir, default = TRUE )
Directory C:\Users\Witek\AppData\Local\Temp\RtmpAvZhoC\file13a4318c3a4c did not exist. Forced to create a new directory.
> htestcorMd5hash <- saveToRepo( htestcor )
 Show Traceback
 
 Rerun with Debug
 Error in sqliteSendQuery(con, statement, bind.data) : 
  error in statement: near "s": syntax error 
```
The problem seems to be with SQL database but I don't know how to fix it.

**Comment by pbiecek** [comment] 2015-12-04 21:40
The problem is with the function executeSingleQuery,
it does not escape special characters like '
and this is why it breaks with following title:
method:Pearson's product-moment correlation

I will fix it

2015-12-04 18:01 GMT+01:00 Witold Chodor <notifications@github.com>:

> @pbiecek <https://github.com/pbiecek> @MarcinKosinski
> <https://github.com/MarcinKosinski>
> I was trying to extend tags in htest object and I received the following
> error:
>
> > library(archivist)
> Welcome to archivist (version: 1.9.1.1).
> > library(gamair)
> > data(wine)
> > htestcor <- cor.test(wine$year, wine$s.temp, method = "pearson")
> > exampleRepoDir <- tempfile()
> > createEmptyRepo( repoDir = exampleRepoDir, default = TRUE )
> Directory C:\Users\Witek\AppData\Local\Temp\RtmpAvZhoC\file13a4318c3a4c did not exist. Forced to create a new directory.
> > htestcorMd5hash <- saveToRepo( htestcor )
>  Show Traceback
>
>  Rerun with Debug
>  Error in sqliteSendQuery(con, statement, bind.data) :
>   error in statement: near "s": syntax error
>
> The problem seems to be with SQL database but I don't know how to fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/archivist/issues/154#issuecomment-162022106>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by pbiecek** [comment] 2015-12-04 21:47
fixed with fae4d0b25fba0483997f9f8f4754b85f48bee3de

**Comment by wchodor** [comment] 2015-12-04 22:31
Thank you!

**Comment by wchodor** [comment] 2015-12-05 08:40
Extended tags in htest object. Here are the link to commits(I'm sorry for two):
https://github.com/wchodor/archivist/commit/bbfdee7bc5ff217919f0f7502627117e98873648
https://github.com/wchodor/archivist/commit/82411437b41699cfc65725cbf617733439cf5276

**Comment by wchodor** [comment] 2015-12-05 08:54
@pbiecek @MarcinKosinski 
In this commit : https://github.com/wchodor/archivist/commit/0699198461d4698b8487d7d2c85eca427aa4fd2a I extended tags in lm object. After a while I realised that `summary` gives another class `summary.lm` to the object. Taking this into account should we create another method like `extractTags.summary.lm`? Or we should leave this as it is now?

**Comment by MarcinKosinski** [comment] 2015-12-06 11:29
Before going further with that mission, please check the proposition in https://github.com/pbiecek/archivist/issues/162 on a different approach :)

**Comment by MarcinKosinski** [comment] 2015-12-10 15:07
To sum up.
Let's #162 be a different additional approach. Let's do not abandon those tags that we already have.
I think having different tags for `lm` and different for `summary.lm` is OK since they are 2 different classes. So I think it'll be ok to split those tags that you have prepared for `lm` for 2 various objects :)
I think we've discused `htest` class widely, so this will also be done. I'll check new tags propositions for other classes that you have proposed :)

**Comment by MarcinKosinski** [comment] 2015-12-16 17:09
@wchodor do you plan to extend any other methods? Could you sum up which methods have you extended and which should I extend?

**Comment by wchodor** [comment] 2015-12-16 19:50
I extended the following methods:
- `extractTags.lm`
- `extractTags.summary.lm`
- `extractTags.htest`
- `extractTags.lda`
- `extractTags.qda`
- `extractTags.partition`
- `extractTags.glmnet`
- `extractTags.survfit`
I suggest that you extend `extractTags.survfit`. And of course if you have any ideas about the ones I extended.

**Closed** 2015-12-22 18:46 UTC
Labels: To do!
