### ISSUE TITLE
`copyRepo` function copy artifact's copies

### ISSUE THREAD

**Issue by wchodor** [pbiecek/archivist#119] opened 2015-11-04 15:36 UTC
@MarcinKosinski
While I was exploring examples of this function I noticed that not only is it copying artifacts from one Repository'database into another but also copies of these artifacts. I don't think that a user will be interested in both artifact and its copy. Perhaps we should change this functionality?

**Comment by MarcinKosinski** [comment] 2015-11-04 16:16
Thanks for bug diagnostics.
Does it only happen with `.rda` and `.txt` files or there are also extra
rows in `tag` and `artfact` tables in backpack.db?


2015-11-04 16:48 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment] 2015-11-04 16:32
Of course I meant only backpack database. But now I looked into gallery folder and I think we have 
a more serious problem. Look at this:
```
list.files(path = file.path(exampleRepoDir, "gallery"))
[1] "ff575c261c949d073b2895b05d1097c3.rda" "ff575c261c949d073b2895b05d1097c3.txt"
```
There are only two files while in backpack.db there are 445 artifacts.

**Comment by wchodor** [comment] 2015-11-04 16:37
But in copyGithubRepo everything was allright. So it's curious for me. I think that this may be the problem of this graphGallery Repository.

**Comment by MarcinKosinski** [comment] 2015-11-04 16:56
I don't understand the problem. It is not clever for me what should be
changed. What ix exampleRepoDir now?
Can you provide a reproducible example with code and results?

If there is only a problem of duplicated rows in `tag` and `artifact` then
we should add `distinct` in insert and the problem will be fixed.



2015-11-04 17:37 GMT+01:00 Witold Chodor <notifications@github.com>:

**Comment by wchodor** [comment] 2015-11-04 17:03
```
# creating example Repository

exampleRepoDir <- tempdir()
createEmptyRepo( exampleRepoDir )

# Searching for md5hashes of artifacts (without data related to them)
# in the graphGallery  Repository
archivistRepo <- system.file( "graphGallery", package = "archivist")
hashes <- searchInLocalRepo( pattern="name",
                             repoDir =  archivistRepo,
                             fixed=FALSE )

# Copying selected artifacts from archivist Github  Repository into exampleRepoDir Repository

copyLocalRepo( repoFrom = archivistRepo, repoTo = exampleRepoDir , md5hashes = hashes )

# See how the backpack database in our exampleRepoDir Repository looks like
showLocalRepo( repoDir = exampleRepoDir )
list.files(path = file.path(exampleRepoDir, "gallery"))
```

**Comment by wchodor** [comment] 2015-11-04 17:05
I think that the problem is in copying artifacts from graphGallery.

**Comment by MarcinKosinski** [comment] 2015-11-04 17:45
Do you have the same output as me?

Can you post the same code with results? (I've copied code from RStudio's Console)
````{R}
Restarting R session...

> library(archivist)
Welcome to archivist (version: 1.8.8.2).
> library(archivist)
> 
> # creating example Repository
> 
> exampleRepoDir <- tempdir()
> createEmptyRepo( exampleRepoDir )
> 
> # Searching for md5hashes of artifacts (without data related to them)
> # in the graphGallery  Repository
> archivistRepo <- system.file( "graphGallery", package = "archivist")
> hashes <- searchInLocalRepo( pattern="name",
+                              repoDir =  archivistRepo,
+                              fixed=FALSE )
> 
> # Copying selected artifacts from archivist Github  Repository into exampleRepoDir Repository
> 
> copyLocalRepo( repoFrom = archivistRepo, repoTo = exampleRepoDir , md5hashes = hashes )
> 
> # See how the backpack database in our exampleRepoDir Repository looks like
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> showLocalRepo( repoDir = exampleRepoDir ) %>% nrow
[1] 445
> showLocalRepo( repoDir = exampleRepoDir ) %>% unique %>% nrow
[1] 314
> showLocalRepo( repoDir = exampleRepoDir ) %>% select(md5hash, name) %>% unique %>% nrow
[1] 30
> 
> 
> showLocalRepo( repoDir = archivistRepo ) %>% nrow
[1] 446
> showLocalRepo( repoDir = archivistRepo ) %>% unique %>% nrow
[1] 315
> showLocalRepo( repoDir = archivistRepo ) %>% select(md5hash, name) %>% unique %>% nrow
[1] 31
> 
> list.files(path = file.path(exampleRepoDir, "gallery"))
[1] "ff575c261c949d073b2895b05d1097c3.rda" "ff575c261c949d073b2895b05d1097c3.txt"
> 
> 
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=pl_PL.UTF-8       LC_NUMERIC=C               LC_TIME=pl_PL.UTF-8       
 [4] LC_COLLATE=pl_PL.UTF-8     LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=pl_PL.UTF-8   
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3       archivist_1.8.8.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1       lubridate_1.3.3   assertthat_0.1    digest_0.6.8     
 [5] bitops_1.0-6      R6_2.1.1          plyr_1.8.3        jsonlite_0.9.17  
 [9] DBI_0.3.1         git2r_0.11.0      magrittr_1.5      RSQLite_1.0.0    
[13] httr_1.0.0        stringi_1.0-1     lazyeval_0.1.10   rstudioapi_0.3.1 
[17] tools_3.2.2       stringr_1.0.0     RCurl_1.95-4.7    parallel_3.2.2   
[21] memoise_0.2.1     knitr_1.11.2      rstudio_0.98.1103
````

**Comment by wchodor** [comment] 2015-11-04 17:58
Exactly the same. 
I am  curious about this one file that was missing in exampleRepoDir.
What do you think about it ? 
We will have another issue to resolve.

**Comment by MarcinKosinski** [comment] 2015-11-04 17:59
And please tell me if the corresponding result for new version `1.8.8.3` solves the problem (I've added `DISTINCT` to copy statement https://github.com/pbiecek/archivist/commit/34dd59925d980c78ada83caafa50284857df480c


````R
Restarting R session...

> library(archivist)
Welcome to archivist (version: 1.8.8.3).
> # creating example Repository
> 
> exampleRepoDir <- tempdir()
> createEmptyRepo( exampleRepoDir )
> 
> # Searching for md5hashes of artifacts (without data related to them)
> # in the graphGallery  Repository
> archivistRepo <- system.file( "graphGallery", package = "archivist")
> hashes <- searchInLocalRepo( pattern="name",
+                              repoDir =  archivistRepo,
+                              fixed=FALSE )
> 
> # Copying selected artifacts from archivist Github  Repository into exampleRepoDir Repository
> 
> copyLocalRepo( repoFrom = archivistRepo, repoTo = exampleRepoDir , md5hashes = hashes )
> 
> # See how the backpack database in our exampleRepoDir Repository looks like
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> showLocalRepo( repoDir = exampleRepoDir ) %>% nrow
[1] 314
> showLocalRepo( repoDir = exampleRepoDir ) %>% unique %>% nrow
[1] 314
> showLocalRepo( repoDir = exampleRepoDir ) %>% select(md5hash, name) %>% unique %>% nrow
[1] 30
> 
> 
> showLocalRepo( repoDir = archivistRepo ) %>% nrow
[1] 446
> showLocalRepo( repoDir = archivistRepo ) %>% unique %>% nrow
[1] 315
> showLocalRepo( repoDir = archivistRepo ) %>% select(md5hash, name) %>% unique %>% nrow
[1] 31
> 
> list.files(path = file.path(exampleRepoDir, "gallery"))
[1] "ff575c261c949d073b2895b05d1097c3.rda"
[2] "ff575c261c949d073b2895b05d1097c3.txt"
> 
> 
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=pl_PL.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pl_PL.UTF-8        LC_COLLATE=pl_PL.UTF-8    
 [5] LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=pl_PL.UTF-8   
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] dplyr_0.4.3       archivist_1.8.8.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1       lubridate_1.3.3   assertthat_0.1   
 [4] digest_0.6.8      bitops_1.0-6      R6_2.1.1         
 [7] plyr_1.8.3        jsonlite_0.9.17   DBI_0.3.1        
[10] git2r_0.11.0      magrittr_1.5      RSQLite_1.0.0    
[13] httr_1.0.0        stringi_1.0-1     lazyeval_0.1.10  
[16] rstudioapi_0.3.1  tools_3.2.2       stringr_1.0.0    
[19] RCurl_1.95-4.7    parallel_3.2.2    memoise_0.2.1    
[22] knitr_1.11.2      rstudio_0.98.1103
````

**Comment by MarcinKosinski** [comment] 2015-11-04 18:02
But it looke like not all files are being copied

````R
> list.files(path = file.path(exampleRepoDir, "gallery")) %>% length
[1] 2
> list.files(path = file.path(archivistRepo, "gallery")) %>% length
[1] 54
> list.files(path = file.path(archivistRepo, "gallery")) %>% unique %>% length
[1] 54
````

**Comment by MarcinKosinski** [comment] 2015-11-04 18:25
Ok now it looks like we almost are coping all files :)

````R
Restarting R session...

> library(archivist)
Welcome to archivist (version: 1.8.8.4).
> 
> # creating example Repository
> 
> exampleRepoDir <- tempdir()
> createEmptyRepo( exampleRepoDir )
> 
> # Searching for md5hashes of artifacts (without data related to them)
> # in the graphGallery  Repository
> archivistRepo <- system.file( "graphGallery", package = "archivist")
> hashes <- searchInLocalRepo( pattern="name",
+                              repoDir =  archivistRepo,
+                              fixed=FALSE )
> 
> # Copying selected artifacts from archivist Github  Repository into exampleRepoDir Repository
> 
> copyLocalRepo( repoFrom = archivistRepo, repoTo = exampleRepoDir , md5hashes = hashes )
> 
> # See how the backpack database in our exampleRepoDir Repository looks like
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> showLocalRepo( repoDir = exampleRepoDir ) %>% nrow
[1] 314
> showLocalRepo( repoDir = exampleRepoDir ) %>% unique %>% nrow
[1] 314
> showLocalRepo( repoDir = exampleRepoDir ) %>% select(md5hash, name) %>% unique %>% nrow
[1] 30
> 
> 
> showLocalRepo( repoDir = archivistRepo ) %>% nrow
[1] 446
> showLocalRepo( repoDir = archivistRepo ) %>% unique %>% nrow
[1] 315
> showLocalRepo( repoDir = archivistRepo ) %>% select(md5hash, name) %>% unique %>% nrow
[1] 31
> 
> list.files(path = file.path(exampleRepoDir, "gallery")) %>% length
[1] 51
> list.files(path = file.path(archivistRepo, "gallery")) %>% length
[1] 54
> list.files(path = file.path(archivistRepo, "gallery")) %>% unique %>% length
[1] 54
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=pl_PL.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pl_PL.UTF-8        LC_COLLATE=pl_PL.UTF-8    
 [5] LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=pl_PL.UTF-8   
 [7] LC_PAPER=pl_PL.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] dplyr_0.4.3       archivist_1.8.8.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1       lubridate_1.3.3   assertthat_0.1   
 [4] digest_0.6.8      bitops_1.0-6      R6_2.1.1         
 [7] plyr_1.8.3        jsonlite_0.9.17   DBI_0.3.1        
[10] git2r_0.11.0      magrittr_1.5      RSQLite_1.0.0    
[13] httr_1.0.0        stringi_1.0-1     lazyeval_0.1.10  
[16] rstudioapi_0.3.1  tools_3.2.2       stringr_1.0.0    
[19] RCurl_1.95-4.7    parallel_3.2.2    memoise_0.2.1    
[22] knitr_1.11.2      rstudio_0.98.1103
````

**Comment by MarcinKosinski** [comment] 2015-11-13 19:47
I'll look at this in a few days

**Comment by MarcinKosinski** [comment] 2015-11-15 17:26
@wchodor there was no bug. This function works properly. The difference in the number of unique artifacts before coping and after coping came from the `pattern` of search statement.
In archivist repository there are 30 unique artifacts and 1 related dataset. Search statement was specified only for artifacts that has a tag starting from `name` - a related dataset has no tags starting from 'name' as it's only has one tags starting with `relatedTo`. So we have only copied artifacts and not they're related datasets. If one would like to copy also those related datasets he should use `multiSearch` as in that example. Do you think I should add such info in the manual of `copy` function? I think the case is closed, but the matter is the extension of the `copy*Repo` function's docuemantation page.

````{R}
Restarting R session...

> library(archivist)
Welcome to archivist (version: 1.8.9.5).
> exampleRepoDir <- tempfile()
> createEmptyRepo( exampleRepoDir )
Directory C:\Users\Marcin\AppData\Local\Temp\RtmpEx6X69\file19107b06d75 did not exist. Forced to create a new directory.
> archivistRepo <- system.file( "graphGallery", package = "archivist")
> searchInLocalRepo( pattern="name",
+                    repoDir =  archivistRepo,
+                    fixed=FALSE ) -> hashes
> copyLocalRepo( repoFrom = archivistRepo, repoTo = exampleRepoDir , md5hashes = hashes )
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> 
> # let's check the number of unique rows
> showLocalRepo( repoDir = exampleRepoDir ) %>% select(md5hash, name) %>% unique %>% nrow
[1] 30
> showLocalRepo( repoDir = archivistRepo ) %>% select(md5hash, name) %>% unique %>% nrow
[1] 31
> 
> 
> # let's check tags of tne one artifact that is not copied
> showLocalRepo( repoDir = exampleRepoDir ) %>% select(md5hash, name) %>% unique -> archiv1
> showLocalRepo( repoDir = archivistRepo ) %>% select(md5hash, name) %>% unique -> archiv2
> setdiff(archiv2, archiv1)
                           md5hash                             name
1 c112c80ae9039b658149e1d66e7507e9 c112c80ae9039b658149e1d66e7507e9
> getTagsLocal('c112c80ae9039b658149e1d66e7507e9', repoDir = archivistRepo)
character(0)
>  # no tgas
> showLocalRepo(archivistRepo, method = 'tags') %>%
+   filter(artifact == 'c112c80ae9039b658149e1d66e7507e9')
                          artifact                                           tag         createdDate
1 c112c80ae9039b658149e1d66e7507e9 relationWith:6dcb47aaff74b1b5f292b3eddc471c17 2014-09-03 00:13:21
> # so it's a related dataset
> 
> # So if one wants to copy all artifacts and related datasets, then he should hit
> multiSearchInLocalRepo(patterns = c('name', 'relationWith'),
+                        archivistRepo,
+                        intersect = FALSE,
+                        fixed = FALSE) -> hashes_of_artifacts_and_datasets
> length(hashes)
[1] 27
> length(hashes_of_artifacts_and_datasets)
[1] 28

````

**Comment by wchodor** [comment] 2015-11-15 18:25
So where this difference comes from?
```
> list.files(path = file.path(exampleRepoDir, "gallery")) %>% length
[1] 51
> list.files(path = file.path(archivistRepo, "gallery")) %>% length
[1] 54
> list.files(path = file.path(archivistRepo, "gallery")) %>% unique %>% length
[1] 54
```

**Comment by wchodor** [comment] 2015-11-15 18:45
@MarcinKosinski 
Well done. It's a good explanation.
I think that if we want to copy Repository then we want to copy artifacts as well as datasets in relation with this artifacts. It is very good that you figured out this problem and it may be instructive to inform user about it.

**Comment by MarcinKosinski** [comment] 2015-11-15 21:08
It wasn't a problem. We were copying only artifacts. 
Ok I'll add this suggestion to the documentation page, but there are some artifacts archived with `%a%` operator that does not have a name neither `relationWith` tag, so we still are not able to copy whole repostiory in this way

**Comment by wchodor** [comment] 2015-11-15 21:15
So perhaps it's better to use `unique(showLocalRepo(exampleRepo)[,1])`

**Comment by MarcinKosinski** [comment] 2015-11-16 18:31
fixed with https://github.com/pbiecek/archivist/commit/b43911f4e35600cb70cabbfabb7455e5dedac9bc

**Closed by MarcinKosinski** 2015-11-16 18:31 UTC
Labels: To do!
